config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  devise_for :users
  root "users#index"

  resources :users, only: %i[index show] do
    resources :posts, only: %i[index show new create destroy] do
      resources :likes, only: %i[create]
      resources :comments, only: %i[create destroy]
    end
  end

  namespace :api do
    resources :users, only: %i[index show] do
      resources :posts, only: %i[index] do
        resources :comments, only: %i[index create]
      end
    end
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
    if user.admin?
      can :manage, :all
    else
      can :destroy, Post do |post|
        post.author_id == user.id
      end

      can :destroy, Comment do |comment|
        comment.author_id == user.id
      end

      can :create, Post do |_post|
        user.id
      end

      can :create, Comment do |_comment|
        user.id
      end

      can :read, :all
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post

  def comment_count(id)
    counts = Comment.where(post_id: id).count
    post = Post.find(id)
    post.update(comments_counter: counts)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post

  def like_count(id)
    counts = Like.where(post_id: id).count
    post = Post.find(id)
    post.update(likes_counter: counts)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :comments
  has_many :likes

  validates :title, presence: true, length: { maximum: 250 }
  validates :comments_counter, :likes_counter, presence: true,
                                               numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def update_counter(id)
    counts = Post.where(author_id: id).count
    user = User.find(id)
    user.update(posts_counter: counts)
  end

  def five_recent_comment(post_id)
    Comment.where(post_id: post_id).order(created_at: :desc).first(5)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_many :posts, foreign_key: 'author_id'
  has_many :comments, foreign_key: 'author_id'
  has_many :likes, foreign_key: 'author_id'

  validates :name, presence: true
  validates :posts_counter, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def admin?
    role == 'admin'
  end

  def three_recent_post(user_id)
    Post.order(updated_at: :desc).where(author_id: user_id).first(3)
  end
end

app/controllers/api/comments_controller.rb
class Api::CommentsController < ApplicationController
  before_action :authorize_request
  protect_from_forgery with: :null_session

  def index
    @comments = Comment.where(post_id: params[:post_id])

    if @comments.empty?
      json_response({ msg: 'No post, comments or user found' }, 400)
    else
      render json: @comments
    end
  end

  def create
    @comment = Comment.create(
      text: comment_params[:text],
      author_id: params[:user_id],
      post_id: params[:post_id]
    )

    json_response(@comment, :created)
  end

  private

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/api/posts_controller.rb
class Api::PostsController < ApplicationController
  before_action :authorize_request

  def index
    @posts = Post.where(author_id: params[:user_id])

    if @posts.empty?
      json_response({ msg: 'no post or user found' }, 400)
    else
      render json: @posts
    end
  end
end

app/controllers/api/users_controller.rb
class Api::UsersController < ApplicationController
  before_action :authorize_request

  def index
    json_response({ msg: 'welcome to our API' })
  end

  def show
    json_response({ msg: 'to see the posts add /posts' })
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Response
  include ExceptionHandler
  protect_from_forgery with: :exception

  before_action :update_allowed_parameters, if: :devise_controller?

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :bio, :photo, :email, :password) }
    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:name, :bio, :photo, :email, :password, :current_password)
    end
  end

  def authorize_request
    header = request.headers['Auth']
    header = header.split.last if header
    begin
      @decoded = JsonWebToken.decode(header)
      p @decoded
      @current_user = User.find(@decoded['id'])
    rescue ActiveRecord::RecordNotFound => e
      render json: { errors: e.message }, status: :unauthorized
    rescue JWT::DecodeError => e
      render json: { error: e.message }, status: :unauthorized
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  load_and_authorize_resource except: :create

  def create
    @comment = Comment.new(
      text: allowed_params[:text],
      author_id: params[:user_id],
      post_id: params[:post_id]
    )
    if @comment.save
      @comment.comment_count(params[:post_id])
      redirect_to user_post_path(params[:user_id], params[:post_id])
    else
      redirect_to user_post_path(params[:user_id])
    end
  end

  def destroy
    @comment = Comment.find_by(id: params[:id])

    if @comment.destroy
      redirect_to user_post_path(params[:user_id], params[:post_id]), status: 303
      flash[:notice] = 'Successfully deleted comment.'
    else
      render :new
    end
  end

  private

  def allowed_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/concerns/exception_handler.rb
module ExceptionHandler
  # provides the more graceful `included` method
  extend ActiveSupport::Concern

  included do
    rescue_from ActiveRecord::RecordNotFound do |e|
      json_response({ message: e.message }, :not_found)
    end

    rescue_from ActiveRecord::RecordInvalid do |e|
      json_response({ message: e.message }, :unprocessable_entity)
    end
  end
end

app/controllers/concerns/response.rb
module Response
  def json_response(object, status = :ok)
    render json: object, status: status
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def new
    @like = Like.new
  end

  def create
    @like = Like.new(
      author_id: params[:user_id],
      post_id: params[:post_id]
    )
    if @like.save
      @like.like_count(params[:post_id])
      redirect_to user_post_path(params[:user_id], params[:post_id])
    else
      redirect_to user_post_path(params[:user_id])
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  load_and_authorize_resource except: :create

  def index
    @user = User.find(params[:user_id])
    @posts = @user.posts.includes(:comments)
  end

  def show
    @post = Post.find_by(id: params[:id])
    @user = User.find(params[:user_id])
  end

  def new
    @post = Post.new
    @user = User.find(params[:user_id])
  end

  def create
    @user = User.find(params[:user_id])
    @post = @user.posts.new(allowed_params)
    # @post = @user.posts.new(
    #   title: allowed_params[:title],
    #   text: allowed_params[:text],
    #   author_id: allowed_params[:user_id],
    #   comments_counter: 0,
    #   likes_counter: 0
    # )
    @post.author_id = params[:user_id]
    if @post.save
      @post.update_counter(params[:user_id])
      redirect_to user_posts_path(@user.id)
      flash[:notice] = 'Your post was successfully created'
    else
      redirect_to new_user_post_path(@user.id)
      flash[:notice] = 'An error has occurred while creating the post'
    end
  end

  def destroy
    @post = Post.find(params[:id])

    if @post.destroy
      @post.update_counter(params[:user_id])
      redirect_to root_path, status: 303
      flash[:notice] = 'post deleted successfully'
    else
      render :new
    end
  end

  private

  def allowed_params
    params.require(:post).permit(:title, :text)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/helper/_comment_form.html.erb
<%= form_with model: @comment, url: "/users/#{@user.id}/posts/#{@post.id}/comments", scope: :comment  do |form| %>
  <h3>New Comment</h3>
  <%= form.text_field :text, placeholder: 'comment...'%>
  <%= form.submit "Create Comment" %>
<% end %>

app/views/helper/_delete_post.erb
<% if can? :destroy, @post%>
  <%= link_to user_post_path(@user, @post), data:{"turbo-method": :delete}, class: "trash" do%>
    <svg style="width:24px;height:24px" viewBox="0 0 24 24">
      <path fill="currentColor" d="M19,4H15.5L14.5,3H9.5L8.5,4H5V6H19M6,19A2,2 0 0,0 8,21H16A2,2 0 0,0 18,19V7H6V19Z" />
    </svg>
  <%end%>
<% end %>

app/views/helper/_like_form.html.erb
<%= form_with model: @like, url: "/users/#{@user.id}/posts/#{@post.id}/likes", scope: :like  do |form| %>
  <button type="submit" class='svg'>
    <svg style="width:24px;height:24px" viewBox="0 0 24 24">
      <path fill="currentColor" d="M5,9V21H1V9H5M9,21A2,2 0 0,1 7,19V9C7,8.45 7.22,7.95 7.59,7.59L14.17,1L15.23,2.06C15.5,2.33 15.67,2.7 15.67,3.11L15.64,3.43L14.69,8H21C22.11,8 23,8.9 23,10V12C23,12.26 22.95,12.5 22.86,12.73L19.84,19.78C19.54,20.5 18.83,21 18,21H9M9,19H18.03L21,12V10H12.21L13.34,4.68L9,9.03V19Z" />
    </svg>
  </button>
<%end%>

app/views/helper/_post_form.html.erb
<%= form_with model: @post, url: user_posts_path(@user.id), scope: :post  do |form| %>
  <h3>New Post</h3>
  <%= form.text_field :title, placeholder: 'Post Title'%>
  <%= form.text_area :text, placeholder: 'Post Content' %>
  <%= form.submit "Create Post" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsBlogApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%
=begin%>
 <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p> 
<%
=end%>

    <% flash.each do |name, msg| -%>
      <p class="notification"><%= msg %></p>
    <% end -%>

    <%= yield %>
  </body>
</html>

app/views/posts/index.html.erb
<section class='container'>
  <div class='new_post'>
    <button type='button'><%= link_to "create new post",  new_user_post_path(@user.id) %></button>
  </div>
  <div class='user_card'>
    <img src="<%= @user.photo %>" alt='User Avatar' />

    <div class='user_details'>
      <h1><%= @user.name %></h1>
      <p>Number of posts: <%= @user.posts_counter || 0 %></p>
    </div>
  </div>

  <% @user.three_recent_post(@user.id).each do |post| %>
    <div class='post_card'>
      <% @post = post%>
      <div class='like'><%= render 'helper/like_form' %></div>
      <a href="/users/<%= @user.id %>/posts/<%= post.id %>"><h3><%= post.title %></h3></a>
      <p><%= post.text %></P>
    </div>
    <%if Comment.all.where(post_id: post.id).length != 0 %>
      <div class='comment_card'>
        <% Comment.all.where(post_id: post.id).each do |comment| %>
          <% user = User.all.find(comment.author_id) %>
          <p><b><%= user.name %>: </b><%= comment.text %></p>
        <%end%>
      </div>
    <%end%>
  <%end%>

  <button type='button'>load more</button>
</section>

app/views/posts/new.html.erb
<div>
  <%= render 'helper/post_form' %>
</div>

app/views/posts/show.html.erb
<section class='container'>
  <div class='post_card'>
    <div class='like'>
      <%= render 'helper/like_form' %>
      <%= render 'helper/delete_post' %>
    </div>
    <div class='details'>
      <h3><%= @post.title %> <p>by <%= User.all.find(@post.author_id).name %></p></h3>
      <p>Comments: <%= @post.comments_counter||0 %>, Likes: <%= @post.likes_counter||0 %></p>
    </div>
    <p><%= @post.text %></P>
  </div>
  <div class='line'>
    <%= render 'helper/comment_form' %>
  </div>
  <%if Comment.all.where(post_id: @post.id).length != 0 %>
    <div class='comment_card'>
      <% Comment.all.where(post_id: @post.id).each do |comment| %>
        <% user = User.all.find(comment.author_id) %>
        <p><b><%= user.name %>: </b><%= comment.text %></p>
        <% if can? :destroy, comment %>
          <%= link_to "Delete Comment", user_post_comment_path(@user, @post, comment), data:{"turbo-method": :delete} %>
        <% end %>
      <%end%>
    </div>
  <%end%>
</section>

app/views/users/index.html.erb
<section class='container'>
  <h1>Users List</h1>
  <% @users.each do |user| %>
    <div class='user_card'>
      <img src="<%= user.photo %>" alt='User Avatar' />

      <div class='user_details'>
        <h1><%= link_to user.name, user_path(user.id) %></h1>
        <p>Number of Posts: <%= user.posts_counter || 0 %></p>
      </div>
    </div>
  <%end%> 
</section>

app/views/users/posts.html.erb
<section class='container'>
  <div class='user_card'>
    <img src="<%= @user.photo %>" alt='User Avatar' />

    <div class='user_details'>
      <h1><%= @user.name %></h1>
      <p>Number of posts: <%= @user.posts_counter || 0 %></p>
    </div>
  </div>

  <% @user.three_recent_post(@user.id).each do |post| %>
    <div class='post_card'>
      <a href="/users/<%= @user.id %>/posts/<%= post.id %>"><h3><%= post.title %></h3></a>
      <p><%= post.text %></P>
    </div>
    <%if Comment.all.where(post_id: post.id).length != 0 %>
      <div class='comment_card'>
        <% Comment.all.where(post_id: post.id).each do |comment| %>
          <% user = User.all.find(comment.author_id) %>
          <p><b><%= user.name %>: </b><%= comment.text %></p>
        <%end%>
      </div>
    <%end%>
  <%end%>

  <button type='button'>load more</button>
</section>

app/views/users/show.html.erb
<section class='container'>
  <div class='new_post'>
    <button type='button'><%= link_to "create new post",  new_user_post_path(@user.id) %></button>
  </div>
  <div class='user_card'>
    <img src="<%= @user.photo %>" alt='User Avatar' />

    <div class='user_details'>
      <h1><%= @user.name %></h1>
      <p>Number of posts: <%= @user.posts_counter || 0 %></p>
    </div>
  </div>

  <div class='bio'>
    <h3>Bio:</3>
    <p><%= @user.bio %></p>
  </div>

  <% @user.three_recent_post(@user.id).each do |post| %>
    <div class='post_card'>
      <% @post = post%>
      <div class='like'><%= render 'helper/like_form' %></div>
      <h3><%= link_to post.title, user_post_path(@user.id,post.id) %></h3>
      <p><%= post.text %></P>
      <span>Comments: <%= post.comments_counter||0 %>, Likes: <%= post.likes_counter||0 %></span>
    </div>
  <%end%>
  <button type='button'><%= link_to "see all posts", user_posts_path(@user.id) %></button>
</section>